version: "2"
services:
  db:
    image: mysql:5.6
    container_name: snipeit-db
    hostname: snipeit-db
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=teste
        - MYSQL_DATABASE=teste
        - MYSQL_USER=teste
        - MYSQL_PASSWORD=teste
    volumes:
     - snipeit-db-vol:/var/lib/mysql
    networks:
      snipeit:
        aliases:
          - db

  server:
    image: snipe/snipe-it
    container_name: snipeit-server
    hostname: snipeit-server
    restart: always
    depends_on:
      - db
    environment:
      # remember to set the proper configs on mail server 
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:D5oGA+zhFSVA3VwuoZoQ21RAcwBtJv/RGiqOcZ7BUvI=
      - APP_URL=https://localhost/
      - APP_TIMEZONE=America/Recife
      - APP_LOCALE=pt-BR
      - DB_HOST=db
      - DB_CONNECTION=mysql
      - MYSQL_ROOT_PASSWORD=teste
      - MYSQL_DATABASE=teste
      - MYSQL_USER=teste
      - MYSQL_PASSWORD=teste
      - MAIL_PORT_587_TCP_ADDR=
      - MAIL_PORT_587_TCP_PORT=
      - MAIL_ENV_FROM_ADDR=
      - MAIL_ENV_USERNAME=
      - MAIL_ENV_PASSWORD=
      - MAIL_ENV_FROM_NAME=
      - MAIL_ENV_ENCRYPTION=
    ports:
      # change ports as you wish
      - "8082:443"
    volumes:
      # copy certs to snipeit-server (check on documentation for correct naming)
     - ./certs/:/var/lib/snipeit/ssl/
    networks:
      - snipeit

volumes:
  snipeit-db-vol:

networks:
  snipeit:
    driver: bridge
